# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

from glob import glob
import os
from pathlib import Path
import pkg_resources
import re
import shutil
import subprocess

from jinja2 import Template

from exhale.utils import AVAILABLE_KINDS, qualifyKind

project = "libsonata"
author = "Blue Brain Project, EPFL"
version = pkg_resources.get_distribution("libsonata").version
release = version

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon", "breathe", "exhale"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

master_doc = "index"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx-bluebrain-theme"
html_title = "libsonata"
html_show_sourcelink = False
html_theme_options = {
    "repo_url": "https://github.com/BlueBrain/libsonata/",
    "repo_name": "BlueBrain/libsonata",
}

autodoc_default_options = {"members": True, "imported-members": True}
autodoc_docstring_signature = True

# Setup the breathe extension
breathe_projects = {"libsonata C++ API": "./doxyoutput/xml"}

breathe_default_project = "libsonata C++ API"

# Setup the exhale extension
exhale_args = {
    # These arguments are required
    "containmentFolder": "./cpp",
    "rootFileName": "api.rst",
    "rootFileTitle": "C++ API",
    "doxygenStripFromPath": "..",
    # Suggested optional arguments
    "createTreeView": True,
    # TIP: if using the sphinx-bootstrap-theme, you need
    # "treeViewIsBootstrap": True,
    "exhaleExecutesDoxygen": True,
    "exhaleDoxygenStdin": "INPUT = ../../include",
    "contentsDirectives": False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']


NUMBERED_LINE_RE = re.compile(r"^([1-9]?\d*)(\. )(.*)$")
SELF_ARG_RE = re.compile(r"(self[^),]*(?:, )?)")
FUNCTION_PARTS_RE = re.compile(r"(.*)\((.*)\)")


def _format_signature(match):
    """Apply the correct RST formatting to the signature."""

    sig = "``" + match.group(1) + "``\ ("

    if match.group(2):
        sig += "*" + match.group(2) + "*"

    sig += "\ )"

    return sig


def _process_pybind_docstrings(app, what, name, obj, options, lines):
    """Pre-process the docstrings generated by pybind."""

    # don't show members as being members of libsonata._libsonata.*
    lines[:] = [l.replace("._libsonata", "") for l in lines]

    # pybind uses "Throws" for some reason, change to "Raises"
    if lines:
        lines[:] = ["Raises:" if l == "Throws:" else l for l in lines]

    # only modify pybind overloaded functions
    if lines and lines[0] == "Overloaded function.":
        for index, line in enumerate(lines[1:], start=1):
            # each overload is numbered so check we have a numbered line
            match = NUMBERED_LINE_RE.match(line)

            # we need to indent lines inside overloads since pybind does not
            if match is None:
                if line:
                    lines[index] = "   " + line
                continue

            # remove self arg
            sig = SELF_ARG_RE.sub("", match.group(3))

            # apply formatting
            sig = FUNCTION_PARTS_RE.sub(_format_signature, sig)

            # replace with arrow unicode charater
            sig = sig.replace("->", "\u2192")

            # rebuild the numbered line
            lines[index] = "#" + match.group(2) + sig


def _process_pybind_signature(
    app, what, name, obj, options, signature, return_annotation
):
    """Pre-process signatures to remove the self argument."""

    if signature is None:
        return

    # don't show members as being members of libsonata._libsonata.*
    signature = signature.replace("._libsonata", "")

    if return_annotation:
        return_annotation = return_annotation.replace("._libsonata", "")

    sig = SELF_ARG_RE.sub("", signature)
    return sig, return_annotation


def _write_kind_indices(app):
    root_dir = app.confdir
    template_dir = os.path.join(root_dir, "_templates")

    with open(os.path.join(template_dir, "indices.rst_t")) as template_file:
        template = Template(template_file.read())

    for kind in AVAILABLE_KINDS:

        files = [
            os.path.basename(f)
            for f in glob(os.path.join(root_dir, "cpp", kind + "*.rst"))
        ]

        if not files:
            continue

        title = qualifyKind(kind)

        with open(os.path.join(root_dir, "cpp", "index_%s.rst" % kind), "wb") as file_:
            context = {"kind": kind, "title": title, "files": files}
            file_.write(template.render(**context).encode("utf-8"))


def setup(app):
    app.connect("autodoc-process-docstring", _process_pybind_docstrings)
    app.connect("autodoc-process-signature", _process_pybind_signature)
    app.connect("builder-inited", _write_kind_indices)
